### PR TITLE
Added gitmostwanted.com to websites

### PR DESCRIPTION
**Pull request by kkamkou**
Hi, please review this PR.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Interesting. Do you know how works?

**Comment by kkamkou** [comment]
It uses data from [githubarchive](https://www.githubarchive.org/) (100% deserves to be in this list) [for this](https://github.com/kkamkou/gitmostwanted.com/wiki/Repository-statuses#process).

**Comment by Kikobeats** [comment]
sounds great, but before add into the list I need to understand how works. I enter in the website and I don't see an explanation of the website, filter looks confusing...

I want to add this project, but is not clear the purpose of this. Why is better than the Github Explore in my mail?

**Comment by kkamkou** [comment]
As described, it analyses each repo. calculates variance and can tell you if a repo is useless or not. The conclusion is that the "github trending" is useless. You can check githubarchive, gwm and just decide if it deserves or not. It is up to you.

**Comment by ghost** [comment]
@kkamkou Documentation is skimpy though :sweat_smile:

**Comment by kkamkou** [comment]
@bucaran thank you for the feedback, I've added `What is it?` link (top right corner) with description.

**Pull request closed without merging**
