### PR TITLE
ADD HW section

### PR DESCRIPTION
**Pull request by blackout314**

### CODE REVIEW

**Comment by Kikobeats** [comment]
Thanks! :dancer:

**Comment by blackout314** [comment]
u too :+1:

**Comment by Kikobeats** [comment]
@blackout314 not really! are list of arduino projects... but are not related directly with github 😕

**Comment by blackout314** [comment]
@Kikobeats as u wish.. not my repo (arduino)

**Comment by Kikobeats** [comment]
I feel that a better section to add this repositories could be:

https://github.com/bayandin/awesome-awesomeness
https://github.com/sindresorhus/awesome

**Pull request merged**
